services:
  - type: web
    name: utdrs-core-engine
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGODB_URI
        sync: false  # Set this manually in the Render dashboard
      - key: DB_NAME
        value: utdrs
      - key: API_GATEWAY_URL
        sync: false  # Set this to the deployed API Gateway URL
      - key: JWT_SECRET
        generateValue: true
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
